# Generated by Django 3.0.6 on 2020-05-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('phone_no', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
    ]
