# Generated by Django 3.0.6 on 2020-05-15 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
