# Generated by Django 3.0.6 on 2020-05-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20200515_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_no',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
