# Generated by Django 3.0.6 on 2020-05-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20200517_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nameu',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
