# Generated by Django 3.0.6 on 2020-05-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20200517_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
