# Generated by Django 3.0.6 on 2020-05-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_auto_20200525_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='photo',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
