# Generated by Django 3.0.6 on 2020-06-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_auto_20200527_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
