# Generated by Django 3.0.6 on 2020-06-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_goods_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='amount_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
