# Generated by Django 3.0.6 on 2020-06-21 10:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0025_auto_20200621_1013'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='goods',
            index_together={('name', 'owner')},
        ),
    ]
