# Generated by Django 3.0.6 on 2020-06-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_auto_20200621_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
