# Generated by Django 3.0.6 on 2020-06-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
