# Generated by Django 3.0.6 on 2020-08-02 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0028_remove_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='goods',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='goods',
            index_together=set(),
        ),
    ]
