# Generated by Django 3.0.6 on 2020-08-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_auto_20200802_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
