# Generated by Django 3.0.6 on 2020-08-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_auto_20200816_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordered',
            name='time',
            field=models.TimeField(default='13:12:12'),
        ),
    ]
