# Generated by Django 3.0.6 on 2020-08-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0033_auto_20200822_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordered',
            name='time',
            field=models.TimeField(default='15:28:51'),
        ),
    ]
