# Generated by Django 3.0.6 on 2020-08-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0034_auto_20200822_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='sellerId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordered',
            name='time',
            field=models.TimeField(default='17:41:13'),
        ),
    ]
