# Generated by Django 3.0.6 on 2020-08-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0035_auto_20200822_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='phone_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ordered',
            name='time',
            field=models.TimeField(default='12:15:02'),
        ),
    ]
